export const ROCK_SONG_NAMES: SongInfo[] = [
    { singer: 'Queen', song: 'Bohemian Rhapsody' },
    { singer: 'Led Zeppelin', song: 'Whole lotta love' },
    { singer: 'The Rolling Stones', song: 'Paint It Black' },
    { singer: 'Pink Floyd', song: 'Comfortably Numb' },
    { singer: 'Nirvana', song: 'Smells Like Teen Spirit' },
    { singer: 'The Eagles', song: 'Hotel California' },
    { singer: 'AC/DC', song: 'Back In Black' },
    { singer: 'The Beatles', song: 'Hey Jude' },
    { singer: 'Metallica', song: 'Enter Sandman' },
    { singer: "Guns N' Roses", song: "Sweet Child O' Mine" },
    { singer: 'Lynyrd Skynyrd', song: 'Free Bird' },
    { singer: 'Aerosmith', song: 'Dream On' },
    { singer: 'Bon Jovi', song: "Livin' on a Prayer" },
    { singer: 'Black Sabbath', song: 'Paranoid' },
    { singer: 'SOAD', song: 'Chop Suey' },
    { singer: 'Foo Fighters', song: 'Everlong' },
    { singer: 'Fleetwood Mac', song: 'Go Your Own Way' },
    { singer: 'The Who', song: "Baba O'Riley" },
    { singer: 'Bruce Springsteen', song: 'Born to Run' },
    { singer: 'U2', song: 'With or Without You' },
    { singer: 'Radiohead', song: 'Creep' },
    { singer: 'Red Hot Chili Peppers', song: 'Under the Bridge' },
    { singer: 'Green Day', song: 'Boulevard of Broken Dreams' },
    { singer: 'Pearl Jam', song: 'Alive' },
    { singer: 'The Clash', song: 'London Calling' },
];

export const TIK_TOK_NAMES: SongInfo[] = [
    { singer: 'Doja Cat', song: 'Say So' },
    { singer: 'Megan Thee Stallion', song: 'Savage' },
    { singer: 'The Kid LAROI', song: 'Stay' },
    { singer: 'Lil Nas X', song: 'MONTERO (Call Me By Your Name)' },
    { singer: 'Olivia Rodrigo', song: 'drivers license' },
    { singer: 'Masked Wolf', song: 'Astronaut in the Ocean' },
    { singer: 'Bella Poarch', song: 'Build a B*tch' },
    { singer: 'SZA', song: 'Kill Bill' },
    { singer: 'Billie Eilish', song: 'Happier Than Ever' },
    { singer: 'Coi Leray', song: 'Players' },
    { singer: 'Ariana Grande', song: 'Positions' },
    { singer: 'Glass Animals', song: 'Heat Waves' },
    { singer: 'Steve Lacy', song: 'Bad Habit' },
    { singer: 'Charli XCX', song: 'Boom Clap' },
    { singer: 'Tones and I', song: 'Dance Monkey' },
    { singer: 'Lizzo', song: 'About Damn Time' },
    { singer: 'Jason Derulo', song: 'Savage Love' },
    { singer: 'Surfaces', song: 'Sunday Best' },
    { singer: 'Benny Blanco, Halsey & Khalid', song: 'Eastside' },
    { singer: 'Adele', song: 'Easy on Me' },
    { singer: 'Drake', song: 'Toosie Slide' },
    { singer: 'BTS', song: 'Dynamite' },
    { singer: 'Justin Bieber', song: 'Peaches' },
    { singer: '24kGoldn ft. Iann Dior', song: 'Mood' },
    { singer: 'Jack Harlow', song: 'First Class' },
];

export const OLD_BUT_GOLD_NAMES: SongInfo[] = [
    { singer: 'The Beatles', song: 'Let It Be' },
    { singer: 'Elvis Presley', song: 'Suspicious Minds' },
    { singer: 'The Rolling Stones', song: "(I Can't Get No) Satisfaction" },
    { singer: 'Simon & Garfunkel', song: 'Bridge Over Troubled Water' },
    { singer: 'Marvin Gaye', song: "What's Going On" },
    { singer: 'ABBA', song: 'Dancing Queen' },
    { singer: 'Fleetwood Mac', song: 'Dreams' },
    { singer: 'Queen', song: 'We Will Rock You' },
    { singer: 'The Eagles', song: 'Take It Easy' },
    { singer: 'The Beach Boys', song: 'Good Vibrations' },
    { singer: 'Billy Joel', song: 'Piano Man' },
    { singer: 'David Bowie', song: 'Heroes' },
    { singer: 'Elton John', song: 'Rocket Man' },
    { singer: 'The Temptations', song: 'My Girl' },
    { singer: 'Aretha Franklin', song: 'Respect' },
    { singer: 'Stevie Wonder', song: 'Superstition' },
    { singer: 'Michael Jackson', song: 'Billie Jean' },
    { singer: 'Whitney Houston', song: 'I Wanna Dance with Somebody' },
    { singer: 'Cyndi Lauper', song: 'Girls Just Want to Have Fun' },
    { singer: 'Toto', song: 'Africa' },
    { singer: 'Bonnie Tyler', song: 'Total Eclipse of the Heart' },
    { singer: 'The Police', song: 'Every Breath You Take' },
    { singer: 'Bruce Springsteen', song: 'Born in the U.S.A.' },
    { singer: 'Prince', song: 'Purple Rain' },
    { singer: 'Madonna', song: 'Like a Virgin' },
];
